In [123]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [124]:
df = pd.read_csv('tested_fare_imputed.csv',usecols=['Age','Pclass','Fare','Survived'])
df.head()

   Survived  Pclass   Age     Fare
0         0       3  34.5   7.8292
1         1       3  47.0   7.0000
2         0       2  62.0   9.6875
3         0       3  27.0   8.6625
4         1       3  22.0  12.2875

In [125]:
df.isnull().mean()*100

Survived     0.000000
Pclass       0.000000
Age         20.574163
Fare         0.000000
dtype: float64

In [126]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [127]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
X_train.head()

     Pclass   Age     Fare
280       3  23.0   8.6625
284       3   2.0  20.2125
40        3  39.0  13.4167
17        3  21.0   7.2250
362       2  31.0  21.0000

In [ ]:
knn = KNNImputer(n_neighbors=3,weights='distance') # by default n_neighbors = 5 and weights = uniform
# knn = SimpleImputer() # giving 64 % (less than KNNImputer)
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [129]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

     Pclass        Age     Fare
0       3.0  23.000000   8.6625
1       3.0   2.000000  20.2125
2       3.0  39.000000  13.4167
3       3.0  21.000000   7.2250
4       2.0  31.000000  21.0000
..      ...        ...      ...
329     3.0  29.000000   7.8542
330     1.0  29.307252  31.6833
331     3.0  29.000000   7.9250
332     2.0  24.000000  27.7208
333     1.0  29.307252  27.7208

[334 rows x 3 columns]

In [130]:
lr = LogisticRegression()
lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6428571428571429