In [16]:
import pandas as pd
import numpy as np

In [17]:
data = pd.read_json('airports.json')
data.head()

                                            airports
0  {'code': 'ATL', 'name': 'Hartsfield-Jackson At...
1  {'code': 'PEK', 'name': 'Beijing Capital Inter...
2  {'code': 'DXB', 'name': 'Dubai International',...
3  {'code': 'LAX', 'name': 'Los Angeles Internati...
4  {'code': 'HND', 'name': 'Tokyo Haneda', 'city'...

In [18]:
!pip3 install mysql.connector

Requirement already satisfied: mysql.connector in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.2.9)

In [20]:
import mysql.connector
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')
pd.read_sql_query("SELECT * FROM city WHERE CountryCode='AFG'",conn)

/var/folders/1f/6m1mrc854l70_ftx18ysbs_r0000gn/T/ipykernel_3126/970978277.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode='AFG'",conn)

   ID            Name CountryCode  District  Population
0   1           Kabul         AFG     Kabol     1780000
1   2        Qandahar         AFG  Qandahar      237500
2   3           Herat         AFG     Herat      186800
3   4  Mazar-e-Sharif         AFG     Balkh      127800