In [5]:
import pandas as pd 
import numpy as mp

In [ ]:
# Local CSV file
df = pd.read_csv('coffee.csv')
df.head(2)

      Day Coffee Type  Units Sold
0  Monday    Espresso          25
1  Monday       Latte          15

In [ ]:
# Fetching data from URL
from io import StringIO
import pandas as pd
import requests

url = "https://gist.githubusercontent.com/rnirmal/e01acfdaf54a6f9b24e91ba4cae63518/raw/6b589a5c5a851711e20c5eb28f9d54742d1fe2dc/datasets.csv"

# Optional: Add headers to bypass bot blocks
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
}

# Fetch raw data and convert string text into a file-like object
response = requests.get(url, headers=headers)
dff = pd.read_csv(StringIO(response.text))
dff.head()

,datasetName,about,link,categoryName,cloud,vintage
0,Microbiome Project,American Gut (Microbiome Project),https://github.com/biocore/American-Gut,Biology,GitHub,NaN
1,GloBI,Global Biotic Interactions (GloBI),https://github.com/jhpoelen/eol-globi-data/wik...,Biology,GitHub,NaN
2,Global Climate,Global Climate Data Since 1929,http://en.tutiempo.net/climate,Climate/Weather,NaN,1929.0
3,CommonCraw 2012,3.5B Web Pages from CommonCraw 2012,http://www.bigdatanews.com/profiles/blogs/big-...,Computer Networks,NaN,2012.0
4,Indiana Webclicks,53.5B Web clicks of 100K users in Indiana Univ.,http://cnets.indiana.edu/groups/nan/webtraffic...,Computer Networks,NaN,NaN