In [95]:
import pandas as pd
import numpy as np

In [96]:
df = pd.read_csv('customer.csv')
df.head(10)
# Gender is nominal categorical, Review is Ordinal Categorical, Education is Ordinal Categorical, Purchased is Nominal Categorical

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes
6   18    Male     Good    School        No
7   60  Female     Poor    School       Yes
8   65  Female  Average        UG        No
9   74    Male     Good        UG       Yes

In [97]:
# Here we will apply Nominal Encoding to gender, Ordinal Encoding to review & education, Label Encoding to purchased
df = df.iloc[:,2:]
df.head(10)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No
5  Average    School       Yes
6     Good    School        No
7     Poor    School       Yes
8  Average        UG        No
9     Good        UG       Yes

In [98]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2,random_state=0)
print(X_train.columns)

Index(['review', 'education'], dtype='str')

In [99]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']]) # here the order is 0,1,2 for the Ordinal categorical values
oe.fit(X_train)
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [100]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [101]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [102]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [103]:
X_train

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [104]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])